export const BlendMode = {
  COMPOSITE_BLEND: 0,
  MAXIMUM_INTENSITY_BLEND: 1,
  MINIMUM_INTENSITY_BLEND: 2,
  AVERAGE_INTENSITY_BLEND: 3,
  ADDITIVE_INTENSITY_BLEND: 4,
  INTERPOLATED_BLEND: 5,
  GRADIENT_OPACITY_BLEND: 6,
  CPR_THICKNESS_BLEND: 7,
  RESLICE_MPR_AXIAL_BLEND: 8,
  RESLICE_MPR_CORONAL_BLEND: 9,
  RESLICE_MPR_SAGITTAL_BLEND: 10,
};

export const FilterMode = {
  OFF: 0,
  NORMALIZED: 1,
  RAW: 2,
};

export default {
  BlendMode,
  FilterMode,
};
